import type { DashboardViewModel } from "@/src/features/dashboard/types";

import { memberNavigation } from "./navigation";

export const memberDashboard: DashboardViewModel = {
  role: "member",
  greeting: "Selamat Pagi,",
  userName: "Broto!",
  cooperativeName: "Koperasi Padiwangi",
  period: "0012",
  notificationCount: 0,
  metrics: [],
  actions: [
    {
      label: "Toko & Stok",
      description: "",
      href: "/dashboard/member",
      icon: "savings",
      tone: "teal",
    },
    {
      label: "Transaksi",
      description: "",
      href: "/dashboard/member",
      icon: "loan",
      tone: "blue",
    },
    {
      label: "Laporan",
      description: "",
      href: "/dashboard/member",
      icon: "reports",
      tone: "orange",
    },
  ],
  transactions: [
    {
      id: "member-trx-001",
      href: "/dashboard/member/savings",
      initials: "IN",
      name: "Simpanan Sukarela",
      description: "11 Juni 2026 - Pak Asep",
      amount: "+Rp50.000",
      status: "Masuk",
      statusTone: "success",
      avatarTone: "teal",
      direction: "incoming",
    },
    {
      id: "member-trx-002",
      href: "/dashboard/member/loans",
      initials: "OUT",
      name: "Angsuran Pinjaman",
      description: "11 Juni 2026 - Otomatis",
      amount: "-Rp50.000",
      status: "Keluar",
      statusTone: "warning",
      avatarTone: "teal",
      direction: "outgoing",
    },
    {
      id: "member-trx-003",
      href: "/dashboard/member/savings",
      initials: "IN",
      name: "Simpanan Sukarela",
      description: "11 Juni 2026 - Pak Asep",
      amount: "+Rp50.000",
      status: "Masuk",
      statusTone: "success",
      avatarTone: "teal",
      direction: "incoming",
    },
    {
      id: "member-trx-004",
      href: "/dashboard/member/savings",
      initials: "IN",
      name: "Simpanan Sukarela",
      description: "11 Juni 2026 - Pak Asep",
      amount: "+Rp50.000",
      status: "Masuk",
      statusTone: "success",
      avatarTone: "teal",
      direction: "incoming",
    },
  ],
  navigation: [...memberNavigation],
  memberSummary: {
    title: "Total Saldo Tabungan",
    totalAmount: "Rp 2.450.000",
    primaryMetricLabel: "Simpanan wajib",
    primaryMetricValue: "Rp450.000",
    secondaryMetricLabel: "Simpanan Sukarela",
    secondaryMetricValue: "Rp2.000.000",
  },
  creditProfile: {
    initials: "AA",
    title: "Profil Kredit: Sangat Baik",
    scoreLabel: "MCS 780",
    updatedLabel: "Diperbarui 12 Juni 2026 08.00",
  },
  loanCreditProfile: {
    score: 780,
    maxScore: 850,
    gradeLabel: "Grade AA",
    title: "Profil Kredit Anda: Sangat Baik",
    subtitle: "Member Creditworthiness Score",
    updatedLabel: "Diperbarui 11 Jun 2026 - 09:15",
    factors: [
      { id: "character", label: "Karakter", weightLabel: "35%", score: 88 },
      { id: "capacity", label: "Kapasitas", weightLabel: "30%", score: 88 },
      { id: "capital", label: "Modal", weightLabel: "15%", score: 88 },
      { id: "condition", label: "Kondisi", weightLabel: "12%", score: 88 },
      { id: "collateral", label: "Jaminan", weightLabel: "8%", score: 88 },
    ],
  },
  activeLoanSummary: {
    reference: "Pinjaman Aktif - #P-042",
    amount: "Rp 3.500.000",
    installmentLabel: "Rp 612.000",
    tenorLabel: "0 / 6 bulan",
    dueDateLabel: "1 Juli 2026",
    paidProgressPercent: 0,
    paidProgressLabel: "0% terbayar - Belum ada angsuran",
  },
  loanSchedule: [
    {
      numberLabel: "1",
      scheduleLabel: "1 Juli 2026",
      amountLabel: "Rp 612.000",
      statusLabel: "Lunas",
      statusTone: "success",
    },
    {
      numberLabel: "2",
      scheduleLabel: "1 Agustus 2026",
      amountLabel: "Rp 612.000",
      statusLabel: "Belum",
      statusTone: "muted",
    },
    {
      numberLabel: "3",
      scheduleLabel: "1 September 2026",
      amountLabel: "Rp 612.000",
      statusLabel: "Belum",
      statusTone: "muted",
    },
  ],
  loanHistory: [
    {
      id: "loan-history-042",
      title: "#P-042 - Rp 3.250.000",
      subtitle: "6 bulan - Cicilan berjalan",
      statusLabel: "Dalam proses",
      statusTone: "progress",
    },
    {
      id: "loan-history-041",
      title: "#P-041 - Rp 2.100.000",
      subtitle: "12 bulan - Lunas Mei 2026",
      statusLabel: "Lunas",
      statusTone: "success",
    },
    {
      id: "loan-history-040",
      title: "#P-040 - Rp 1.800.000",
      subtitle: "6 bulan - Lunas Januari 2025",
      statusLabel: "Lunas",
      statusTone: "success",
    },
  ],
  creditAccessSections: [
    {
      id: "requests",
      title: "Permintaan",
      items: [
        {
          id: "akseleran",
          title: "Akseleran",
          subtitle: "Aktif - Sejak 11 Juni 2026 - 30 hari",
          initials: "AA",
          detailHref: "/dashboard/member/loans/access/akseleran?state=pending",
        },
      ],
    },
    {
      id: "active",
      title: "Sedang Aktif",
      items: [
        {
          id: "akseleran-active",
          title: "Akseleran",
          subtitle: "Aktif - Sejak 11 Juni 2026 - 30 hari",
          initials: "AA",
          statusLabel: "Aktif",
          statusTone: "active",
          detailHref: "/dashboard/member/loans/access/akseleran?state=active",
        },
      ],
    },
    {
      id: "history",
      title: "Riwayat",
      items: [
        {
          id: "bpr-sejahtera",
          title: "BPR Sejahtera",
          subtitle: "Kadaluwarsa - 10 Mei 2026",
          initials: "AA",
          statusLabel: "Tidak Aktif",
          statusTone: "inactive",
        },
        {
          id: "jaya-mandiri",
          title: "Jaya Mandiri",
          subtitle: "Kadaluwarsa - 15 April 2025",
          initials: "AB",
          statusLabel: "Tidak Aktif",
          statusTone: "inactive",
        },
        {
          id: "sentosa-prima",
          title: "Sentosa Prima",
          subtitle: "Kadaluwarsa - 1 Januari 2025",
          initials: "AC",
          statusLabel: "Tidak Aktif",
          statusTone: "inactive",
        },
        {
          id: "mega-kencana",
          title: "Mega Kencana",
          subtitle: "Kadaluwarsa - 22 November 2024",
          initials: "AD",
          statusLabel: "Tidak Aktif",
          statusTone: "inactive",
        },
      ],
    },
  ],
  creditAccessDetails: [
    {
      id: "akseleran",
      title: "Akseleran",
      subtitle: "Platform P2P Lending",
      initials: "AA",
      providerLabel: "Terdaftar OJK",
      infoTitle: "Akseleran ingin mengakses data kredit Anda",
      infoDescription: "Untuk menilai kelayakan pinjaman Rp 3.500.000",
      sharedDataItems: [
        "Skor kredit MCS (780 - Grade AA)",
        "Riwayat angsuran (24 bulan)",
        "Saldo tabungan rata-rata 6 bulan",
      ],
      hiddenDataItems: ["Nomor HP & NIK (tidak dibagikan)"],
      durationOptions: ["7 Hari", "14 Hari", "30 Hari"],
      defaultDuration: "7 Hari",
    },
  ],
  savingsHistory: [
    {
      id: "june-2026",
      label: "JUNI 2026",
      transactions: [
        {
          id: "saving-june-11",
          title: "Simpanan Sukarela",
          dateLabel: "11 Juni 2026",
          actorLabel: "Pak Asep",
          dayLabel: "11",
          monthLabel: "JUN",
          amount: "+Rp50.000",
          direction: "incoming",
        },
        {
          id: "saving-june-10",
          title: "Angsuran Pinjaman",
          dateLabel: "10 Juni 2026",
          actorLabel: "Otomatis",
          dayLabel: "10",
          monthLabel: "JUN",
          amount: "-Rp50.000",
          direction: "outgoing",
        },
      ],
    },
    {
      id: "may-2026",
      label: "MEI 2026",
      transactions: [
        {
          id: "saving-may-28",
          title: "Simpanan Sukarela",
          dateLabel: "28 Mei 2026",
          actorLabel: "Pak Asep",
          dayLabel: "28",
          monthLabel: "MEI",
          amount: "+Rp50.000",
          direction: "incoming",
        },
      ],
    },
  ],
};
