import type { StoreDashboardViewModel } from "@/src/features/dashboard/storeTypes";

export const storeDashboardData: StoreDashboardViewModel = {
  dateLabel: "Sabtu, 14 Juni 2026",
  stats: {
    totalCount: 100,
    successCount: 97,
    failedCount: 3,
    lowStockCount: 2,
  },
  alertLabel: "2 Stok Produk Menipis!",
  alertHref: "/dashboard/officer/store/catalog",
  sections: [
    {
      title: "Manajemen Toko",
      actions: [
        {
          label: "Katalog Produk",
          icon: "/ornament/product-catalog.svg",
          href: "/dashboard/officer/store/catalog",
        },
        {
          label: "Kasir",
          icon: "/ornament/cashier.svg",
          href: "/dashboard/officer/store/cashier",
        },
      ],
    },
    {
      title: "Manajemen Stok",
      actions: [
        {
          label: "Stok Masuk",
          icon: "/ornament/stock-in.svg",
          href: "/dashboard/officer/store/stock-in",
        },
        {
          label: "Penyesuaian Stok",
          icon: "/ornament/stock-out.svg",
          href: "/dashboard/officer/store/stock-adjustment",
        },
      ],
    },
  ],
  mutationFilters: [
    { label: "Semua", value: "all" },
    { label: "Stok Masuk", value: "incoming" },
    // { label: "Stok Keluar", value: "outgoing" },
    { label: "Penyesuaian", value: "adjustment" },
  ],
  mutations: [
    {
      id: "store-mutation-001",
      href: "/dashboard/officer/store",
      initials: "BS",
      name: "Budi Setiawan",
      description: "Stok Masuk Beras Premium - 09.12",
      amount: "+50 Kg",
      status: "Sinkron",
      statusTone: "success",
      avatarTone: "blue",
      mutationType: "incoming",
    },
    {
      id: "store-mutation-002",
      href: "/dashboard/officer/store",
      initials: "RP",
      name: "Rahmad Pambudi",
      description: "Penyesuaian Stok Gabah IR64 - 02.12",
      amount: "-20 Kg",
      status: "Pending",
      statusTone: "warning",
      avatarTone: "blue",
      mutationType: "adjustment",
    },
    {
      id: "store-mutation-003",
      href: "/dashboard/officer/store",
      initials: "ST",
      name: "Sari Tanjung",
      description: "Penyesuaian Beras Organik - 01.10",
      amount: "-5 Kg",
      status: "Sinkron",
      statusTone: "success",
      avatarTone: "blue",
      mutationType: "adjustment",
    },
  ],
  productCountLabel: "Menampilkan 5 produk.",
  products: [
    {
      id: "produk-001",
      initials: "BP",
      name: "Beras Premium",
      sku: "ST001",
      stockLabel: "Stok: 90 kg",
      costPrice: "Rp 6.500",
      sellPrice: "Rp 8.000",
      marginLabel: "23%",
      statusLabel: "Stok aman",
      statusTone: "safe",
    },
    {
      id: "produk-002",
      initials: "GI",
      name: "Gabah IR64",
      sku: "ST002",
      stockLabel: "Stok: 90 kg",
      costPrice: "Rp 6.500",
      sellPrice: "Rp 8.000",
      marginLabel: "23%",
      statusLabel: "Menipis",
      statusTone: "low",
    },
    {
      id: "produk-003",
      initials: "BP",
      name: "Beras Premium",
      sku: "ST015",
      stockLabel: "Stok: 150 kg",
      costPrice: "Rp 7.200",
      sellPrice: "Rp 9.500",
      marginLabel: "24%",
      statusLabel: "Stok aman",
      statusTone: "safe",
    },
    {
      id: "produk-004",
      initials: "BO",
      name: "Beras Organik",
      sku: "ST021",
      stockLabel: "Stok: 60 kg",
      costPrice: "Rp 8.000",
      sellPrice: "Rp 11.000",
      marginLabel: "27%",
      statusLabel: "Stok aman",
      statusTone: "safe",
    },
    {
      id: "produk-005",
      initials: "JK",
      name: "Jagung Kering",
      sku: "ST032",
      stockLabel: "Stok: 40 kg",
      costPrice: "Rp 5.500",
      sellPrice: "Rp 7.400",
      marginLabel: "25%",
      statusLabel: "Menipis",
      statusTone: "low",
    },
  ],
};

export const storeUnitOptions = [
  { label: "Kg", value: "Kg" },
  { label: "Liter", value: "Liter" },
  { label: "Pcs", value: "Pcs" },
] as const;

export const storeCategoryOptions = [
  { label: "Pertanian", value: "Pertanian" },
  { label: "Pangan", value: "Pangan" },
  { label: "Retail", value: "Retail" },
] as const;
